### ISSUE TITLE
Build errors on AWS linux

### ISSUE THREAD

**Issue by burlingtonbertie99** [ActivityWatch/aw-server#103]
Hi all - can't build aw-server. 
I get many errors of this nature:

/////////////////////////////////////////////////////////////
cargo build --release --bin aw-server
   Compiling plex v0.2.5
   Compiling url v2.3.1
error[E0658]: use of unstable library feature 'proc_macro_diagnostic'
   --> /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/plex-0.2.5/src/lexer.rs:176:26
    |
176 |                         .error(format!("invalid regular expression: {}", e))
    |                          ^^^^^
    |
    = note: see issue #54140 <https://github.com/rust-lang/rust/issues/54140> for more information
... [ + many similar errors]
/////////////////////////////////////////////////////////////
Debugging info:

(venv) [ec2-user@ip-172-31-62-148 activitywatch]$ ./checkversions.sh 
git version 2.39.1
GNU Make 3.82
Built for x86_64-koji-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Python 3.8.16
Poetry (version 1.3.2)
v16.19.1 (node)
8.19.3	  (npm)
rustc 1.67.1 (d5a82bbd2 2023-02-07)
cargo 1.67.1 (8ecd4f20a 2023-01-10)
/////////////////////////////////////////////////////////////
(venv) [ec2-user@ip-172-31-62-148 activitywatch]$ uname -a
Linux ip-172-31-62-148.us-west-2.compute.internal 4.14.304-226.531.amzn2.x86_64 #1 SMP Wed Feb 1 21:34:38 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
/////////////////////////////////////////////////////////////

I believe I have all the right pre-requisites and versions and have followed your build instructions carefully.

Best regards,

Chris.

**Comment by ErikBjare** [comment]
As the error suggests, you are not running rust nightly. Follow the instructions and use rustup.
