### ISSUE TITLE
Views not working in testing mode

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-server#20]
First off, it simply didn't work, so I got hold of the request URL from the aw-server log and found the response to be:

URL: http://127.0.0.1:5666/api/0/views/aw-webui_windowactivity_summary_erb-main2-arch%3Flimit=-1&start=2017-03-12T00%253A00%253A00%252B01%253A00&end=2017-03-13T00%253A00%253A00%252B01%253A00

    {
        "msg": "There's no view with the name 'aw-webui_windowactivity_summary_erb-main2-arch?limit=-1&start=2017-03-12T00%3A00%3A00%2B01%3A00&end=2017-03-13T00%3A00%3A00%2B01%3A00'"
    }

So, after handcrafting the URL into the following I get another error:

URL: http://127.0.0.1:5666/api/0/views/aw-webui_windowactivity_timeline_erb-main2-arch?limit=-1&start=2017-03-12T00:00:00%2B01:00&end=2017-03-13T00:00:00%2B01:00

    {
        "msg": "Cannot query bucket that doesn't exist in transform: 'aw-watcher-window_erb-main2-arch'"
    }
    

And indeed, aw-watcher-window does not exist since I'm running in testing mode, surely it should work in testing mode as well. 

And also, "that doesn't exist in transform" confused me, I thought the bucket was not **in the transform**, which made no sense to me. Now I realize that what the message tried to say was that the bucket specified in the transform does not exist in the database, which makes sense.

**Comment by ErikBjare** [comment]
Everything seems to work fine in non-testing mode btw.

**Comment by johan-bjareholt** [comment]
This is not a issue with aw-server, but with aw-webui. Apparently somewhere aw-webui does something bad so the view is created with the wrong name or fails to get created at all. I am currently re-writing a lot of that code so let's just wait and see if my next pull request will fix it.

**Comment by johan-bjareholt** [comment]
This should not be an issue anymore, can i close it?

**Comment by ErikBjare** [comment]
I'm getting a 500 error with `{"msg": "Cannot query bucket that doesn't exist in transform: 'aw-watcher-window_erb-laptop-ubuntu'"}` as response when opening `http://127.0.0.1:5666/#!/activity/erb-laptop-ubuntu`. I'm assuming this is due to doing bucket lookup in some weird way and not using the testing bucket when in testing mode.

**Comment by johan-bjareholt** [comment]
Oh, just realized that it's only fixed in dev/next. We can keep this issue open until that is merged.

**Comment by ErikBjare** [comment]
This is fixed, closing.
