### ISSUE TITLE
When aw-qt crashes, aw-server does not shut down

### ISSUE THREAD

**Issue by nikanar** [ActivityWatch/aw-server#31]
Same issue as https://github.com/ActivityWatch/aw-qt/issues/19, only this process is a Flask server, and `run` is inherited from Flask, so I can't put a `if os.getppid() == 1` inside it.

[Flask](http://flask.pocoo.org/snippets/67/) has ways to shut itself down, but typically by setting up a `/shutdown` page that sends the shutdown call when requested, here we don't want to rely on requests, more like setup a watchdog. [Here](https://stackoverflow.com/questions/15562446/how-to-stop-flask-application-without-using-ctrl-c) gives similar options. [There](https://github.com/pallets/flask/issues/1807) my questions is asked, and most of the answer is "app.run() is only meant for development", not too helpful.

Now, does the server really have to be restarted ? Should aw-qt test whether the server is already up, and maybe connect to it rather than start it, if it's already alive ?

**Comment by ErikBjare** [comment]
Isn't it possible to create a thread before running app.run() that acts as
a watchdog and runs os.exit() or something if orphaned?

**Comment by johan-bjareholt** [comment]
@ErikBjare The top answer on the first SO link did it by creating a second process, and a lower rated solution on SO [did it with threads like you mentioned](https://stackoverflow.com/a/45017691/2127148). Should work fine.

**Comment by ErikBjare** [comment]
I think this was solved? If not aw-qt doesn't crash anymore so haven't really seen any instances of this. 

Closing in the meantime since I'm trying to move all actual issues into the main repo. If this remains an problem, open a new issue there and reference this one.
