### ISSUE TITLE
How to implement test cases for watchers

### ISSUE THREAD

**Issue by Otto-AA** [ActivityWatch/aw-server#48]
I am currently writing a few test cases for aw-watcher-terminal and therefore want to check if the events were successfully sent to the server.

In my implementation I need to start aw-server (--testing) and aw-watcher-terminal (--testing). After these are started the python test file then adds a unique id to the event, then fetches the latest 100 events and filters out all events with this id. (Then I can check if all properties of this event are correct)

Do you have a better way to do this?

**Comment by johan-bjareholt** [comment]
Yeah, the state of our integration tests are certainly not optimal right now (we prioritize unittests).
We have also done as you suggested and it works good enough, but there's a lot of room for improvement and things might even be slightly out of date.

Out integration tests are in aw-server, most caveats are in the TODO comments.
https://github.com/ActivityWatch/aw-server/blob/master/tests/test_client.py

We also have a script in the main ActivityWatch repo where we started working on a test_integration test fixture but that never got finished sadly.
https://github.com/ActivityWatch/activitywatch/blob/master/scripts/tests/integration_tests.py

**Comment by Otto-AA** [comment]
Thanks for the info :+1:
