### ISSUE TITLE
aw-server shared library error

### ISSUE THREAD

**Issue by skuzzymiglet** [ActivityWatch/aw-server#68]
I got this in the AW webui:

`Error: Network Error. See dev console (F12) and/or server logs for more info.`

When I ran `aw-server` or `aw-qt` I got:

```
[28038] Error loading Python lib '/usr/bin/libpython3.6m.so.1.0': dlopen: /usr/bin/libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```

It seems `/opt/activitywatch/libpython3.6m.so.1.0` exists though

**Comment by ErikBjare** [comment]
Yeah sorry we messed up v0.9

The issue is being tracked in https://github.com/ActivityWatch/activitywatch/issues/378 and a fix is on the way. It'll hopefully be out tomorrow.
