### ISSUE TITLE
Bind to localhost (prevent access by any other host than localhost) 

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-server#7]
We do NOT have the security to possibly expose a unsecured piece of software on computers.  The sync/security issue is postponed but is critical for many future features (such as sync/networked datastore).

**Comment by ErikBjare** [comment]
The duplicate where this issue was referenced at least had one improvement: the suggestion for SSH forwarding if one wants interhost communication.

**Comment by johan-bjareholt** [comment]
We should probably add a aw-server config just like we do for aw-client and the aw-watchers and make the default to bind to 127.0.0.1/localhost but make it possible to bind to whatever you like

**Comment by ErikBjare** [comment]
@johan-bjareholt Yeah, but I'm closing this issue for now since it's done.

**Comment by johan-bjareholt** [comment]
@ErikBjare That's true. I had forgotten that I had already implemented that in dev/next apparently so the work is already done though which is nice.
