### ISSUE TITLE
Allow user to configure CORS

### ISSUE THREAD

**Issue by dominiwe** [ActivityWatch/aw-server#99]
I saw the documentation for CORS here: https://docs.activitywatch.net/en/latest/security.html#cors-configuration

I am trying to create my own webinterface and I want to configure the server so that my webinterface can access the local API running on `localhost:5600`.

Would it be possible to add a configuration option to set allowed origins in the settings? I suppose it might be good to add this configuration option to `aw-qt`.

**Comment by dominiwe** [comment]
I figured out how to configure it by looking at the source code! For anyone coming across this:

Edit the config `aw-server.toml` and uncomment/add the following:
```toml
[server]
cors_origins = "desired-origin-1,desired-origin-2" # ...
```

Then restart the server.

**Comment by ErikBjare** [comment]
This is also briefly mentioned in the aw-webui README: https://github.com/ActivityWatch/aw-webui/blob/master/README.md#cors

Glad you got it working :)
